utsavjosh1/Portfolio

- app/layout.tsx
- package-lock.json
- package.json
> feat:  added vercel analytics

- app/layout.tsx
> fix: fixed a analytics bug

- app/layout.tsx
- package-lock.json
- package.json
> feat: added speed insight

- app/AboutMe.tsx
- app/Work.tsx
- components/ProjectCard.tsx
- components/Skills.tsx
- components/ui/tabs.tsx
> feat: made some code correction in about me

- components/Title.tsx
> fix: fixed interface issue

- app/Content.tsx
- app/Footer.tsx
- app/globals.css
- app/page.tsx
> 🚑 fix: fixed the whole layout of the page and overwritten code

- app/page.tsx
> fix: Done this responsive

- app/page.tsx
> fix: fixed merge conflict and site is responsive now 🎉🎉

- .eslintrc.json
- .gitignore
- app/AboutMe.tsx
- app/Content.tsx
- app/TypeWriterComponent.tsx
- app/page.tsx
- components/ProjectCard.tsx
- components/Skills.tsx
- package-lock.json
- package.json
- tsconfig.json
- turbo.json
> feat: added turbo repo 🎉🎉

- app/Content.tsx
- app/Experience.tsx
- lib/cloudinary.ts
- next.config.mjs
- package-lock.json
- package.json
> feat: added cloudinary

- app/lib/ui/drawer.tsx
> fix: drawer component

- app/globals.css
- app/page.tsx
- components/bg-video.tsx
> feat: made some responsive changes

- src/app/links/page.tsx
- src/components/banner.tsx
- src/components/under-development.tsx
> feat: corrected the minor issue

- src/app/about/connect.tsx
- src/app/about/page.tsx
- src/app/about/work.tsx
- src/components/image-grid.tsx
- src/components/ui/darkmode.tsx
> (feat): corrected the darkmode for about page

- src/app/about/page.tsx
- src/app/links/page.tsx
- src/components/home/hero-section.tsx
> feat: changed the width made compact

- src/app/about/work.tsx
> update: work internship

- src/app/about/connect.tsx
- src/app/about/page.tsx
- src/app/about/work.tsx
- src/app/links/page.tsx
- src/app/page.tsx
- src/components/home/hero-section.tsx
- src/components/home/project.tsx
- src/components/image-grid.tsx
> feat: changed the whole widthLayout

- src/app/about/page.tsx
- src/components/home/project.tsx
> fix: prod error

- next.config.mjs
- package-lock.json
- package.json
- src/app/about/layout.tsx
- src/app/about/page.tsx
- src/app/api/firebase/config.ts
- src/app/globals.css
- src/app/layout.tsx
- src/components/floating-nav.tsx
- src/components/home/hero-section.tsx
- src/components/image-grid.tsx
- src/components/ui/floating-dock.tsx
- src/config/firebase.ts
> feat: completed the image deployment

- .github/workflows/codeql.yml
> add: added workflow

- README.md
> fix: correct readme

- app/layout.tsx
- app/page.tsx
- hooks/use-mobile.tsx
> fix: added smooth animation to it

- README.md
- app/layout.tsx
- app/me/layout.tsx
- app/page.tsx
- app/socials/page.tsx
- components/about/connect.tsx
- components/floating-nav.tsx
- components/links/SocialLinks.tsx
- config/meta.ts
- config/project.data.ts
- config/site.ts
- config/socialLinks.ts
- package.json
- wrangler.toml
Changed all the social handles
> ref: updated all the social media handles

- API_DOCUMENTATION.md
- OG_IMAGE_DOCUMENTATION.md
- REST_API_SUMMARY.md
- app/api/experience/route.ts
- app/api/og/route.tsx
- app/api/skills/route.ts
- app/api/testimonials/route.ts
- app/blog/page.tsx
- app/experience/page.tsx
- app/page.tsx
- app/projects/[slug]/page.tsx
- lib/api/client.ts
- lib/og-image.ts
- lib/services/experience.ts
- lib/services/skills.ts
- lib/services/testimonials.ts
- package.json
- prisma/seed.ts
[feat: add Prisma seed configuration to package.json](https://github.com/utsavjosh1/Portfolio/commit/2f2b15e91ffbae31ddb1c03e8754d1cb42a1f52c)
> feat: add Prisma seed configuration to package.json 

- app/projects/[slug]/page.tsx
- components/ui/loading-skeleton.tsx
> feat: enhance loading skeleton for project page with detailed sections

- .gitignore
- app/api/technologies/route.ts
- app/layout.tsx
- app/projects/[slug]/page.tsx
- app/projects/page.tsx
- components/tech-stack-carousel.tsx
- config/site.ts
- lib/cache.ts
- lib/services/homepage.ts
- lib/services/technology.ts
- package-lock.json
- public/site.webmanifest
- tailwind.config.ts
- Changed icon size in site.webmanifest from "any" to "32x32".
- Added new scroll animations (scroll-left and scroll-right) to tailwind.config.ts with multiple duration variations for enhanced visual effects.
> fix: update site.webmanifest icon sizes and enhance tailwind animations
